- .github/workflows/release.yml
- Dockerfile
- compose.yaml
- close #16 
- close #17 
---
- arm64アーキテクチャ パッケージの作成
- Dockerfileを修正し、バージョンによって動作するアプリケーションがその時のソースを利用するように修正
> feat: Dockerパッケージ処理の改善

- .github/workflows/release.yml
> feat: リリース本文の変更、リリース時タグの修正

- Dockerfile
- close #22 
以下のエラーを解決したいと思っています:
> chore: Dockerfileにて、libstdc++をインストールするように

- src/main/kotlin/com/jaoafa/vcspeaker/voicetext/NarrationScripts.kt
> fix: GoLive読み上げの接続詞修正

- src/main/kotlin/com/jaoafa/vcspeaker/voicetext/Voice.kt
> chore: change default speed to 120

- src/main/kotlin/com/jaoafa/vcspeaker/models/response/steam/SteamAppDetail.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tools/Steam.kt
- src/main/kotlin/com/jaoafa/vcspeaker/voicetext/textreplacers/UrlReplacer.kt
> feat: steamのゲームなどを特殊読み上げするように

- src/main/kotlin/com/jaoafa/vcspeaker/Main.kt
- src/main/kotlin/com/jaoafa/vcspeaker/commands/JoinCommand.kt
- src/main/kotlin/com/jaoafa/vcspeaker/commands/ResetTitleCommand.kt
- src/main/kotlin/com/jaoafa/vcspeaker/events/SelfVoiceJoinEvent.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tools/discord/DiscordExtensions.kt
- src/main/kotlin/com/jaoafa/vcspeaker/voicetext/Scheduler.kt
VCSpeaker が AFK チャンネルに参加できてしまう問題を修正しました。
> fix: prevent the bot from joining afk channels

- src/main/kotlin/com/jaoafa/vcspeaker/events/NewMessageEvent.kt
- src/main/kotlin/com/jaoafa/vcspeaker/voicetext/Narrator.kt
ignore されたメッセージに 👀 リアクションがつかないようにしました。
これは #44 も解決すると思うのですがどうでしょうか？
> fix: skip ack reaction on ignored messages

- src/main/kotlin/com/jaoafa/vcspeaker/commands/AliasCommand.kt
- src/main/kotlin/com/jaoafa/vcspeaker/commands/IgnoreCommand.kt
- src/main/kotlin/com/jaoafa/vcspeaker/stores/IgnoreStore.kt
- src/main/kotlin/com/jaoafa/vcspeaker/voicetext/TextProcessor.kt
Ignore に完全一致と部分一致判定を実装しました。
「.」が設定されていることによる #44 を解決します。
> feat: Ignore Type

- README.md
> chore: 自動アサインテスト

- src/main/kotlin/com/jaoafa/vcspeaker/events/GoLiveEndEvent.kt
GoLive をしたまま VC を退出した際に通知が出ない問題を解決しました。
> fix: missing GoLive end notification

- src/main/kotlin/com/jaoafa/vcspeaker/commands/VoiceCommand.kt
- src/main/kotlin/com/jaoafa/vcspeaker/stores/VoiceStore.kt
`/voice reset` を実装しました。
加えて、emotion で Normal を指定できるようにしました。
> feat: voice reset

- src/main/kotlin/com/jaoafa/vcspeaker/Main.kt
- src/main/kotlin/com/jaoafa/vcspeaker/VCSpeaker.kt
> feat: add audio configuration options

- src/main/kotlin/com/jaoafa/vcspeaker/Main.kt
- src/main/kotlin/com/jaoafa/vcspeaker/configs/EnvSpec.kt
音質を config.yml からでも設定できるようにしました。
> fix: audio configuration via config.yml

- src/main/kotlin/com/jaoafa/vcspeaker/tts/TextProcessor.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/replacers/AliasReplacer.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/replacers/BaseReplacer.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/replacers/ChannelMentionReplacer.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/replacers/EmojiReplacer.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/replacers/GuildEmojiReplacer.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/replacers/RegexReplacer.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/replacers/ReplacerPriority.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/replacers/RoleMentionReplacer.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/replacers/UrlReplacer.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/replacers/UserMentionReplacer.kt
Replacer の優先度を指定できるようにしました。
一応 Low も入れたんですが使ってません。
システム側 Replacer は High 、ユーザーが指定できるものは Normal にしています。
> feat: Replacer Priority

- .github/workflows/release.yml
> ci: test semantic release

- .github/workflows/release.yml
Semantic Release のテストプルリク(2)です。
> fix: add checkout

- src/main/kotlin/com/jaoafa/vcspeaker/tts/replacers/UrlReplacer.kt
- Web サイトのタイトルを取得する処理で、データ量を 2KB (1024bytes*2) までに制限しました。
- 重複していたコードを一部まとめました。
close #60
> fix: url replacer

- src/main/kotlin/com/jaoafa/vcspeaker/commands/VCSpeakerCommand.kt
- src/main/kotlin/com/jaoafa/vcspeaker/commands/VoiceCommand.kt
> fix: make null emotion selectable as option

- src/main/kotlin/com/jaoafa/vcspeaker/tools/discord/VoiceExtensions.kt
https://github.com/jaoafa/jao-Minecraft-Server/issues/210 の調査のためにデバッグログを出力するようにしました。
> chore: add debug log

- build.gradle.kts
Kord のスナップショット版で Gateway Error が修正されているのでアップデートしました。
> fix: Discord Gateway Error

- src/main/kotlin/com/jaoafa/vcspeaker/stores/VisionApiCounterStore.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/MessageProcessor.kt
> feat: APIの残リクエスト数をフッターに表示するように

- src/main/kotlin/com/jaoafa/vcspeaker/tts/replacers/UrlReplacer.kt
> feat: urlが複数ある場合、特殊読み上げがされない不具合の修正

- .github/workflows/test.yml
- build.gradle.kts
- src/main/kotlin/com/jaoafa/vcspeaker/Main.kt
- src/main/kotlin/com/jaoafa/vcspeaker/VCSpeaker.kt
- src/main/kotlin/com/jaoafa/vcspeaker/configs/EnvSpec.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tools/Serialization.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tools/discord/ChatCommandExtensions.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tools/discord/SlashCommandExtensions.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/TextProcessor.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/api/VoiceTextAPI.kt
- src/test/kotlin/SteamTest.kt
- src/test/kotlin/TextProcessorTest.kt
- src/test/kotlin/YouTubeTest.kt
Kotest と MockK によるテストを実装しました。
現在実装されているのは、
- SteamTest
- YouTubeTest
- TextProcessorTest (Ignore, Alias, URL)
です。
あと Actions にテストワークフローを追加しました。
また、Mock しやすいように Config 周りを少し整理しました。
close #94
> test: add tests for Steam, YouTube, TextProcessor

- .gitignore
- src/main/kotlin/com/jaoafa/vcspeaker/Main.kt
- src/main/kotlin/com/jaoafa/vcspeaker/commands/AliasCommand.kt
- src/main/kotlin/com/jaoafa/vcspeaker/commands/IgnoreCommand.kt
- src/main/kotlin/com/jaoafa/vcspeaker/commands/ParseCommand.kt
- src/main/kotlin/com/jaoafa/vcspeaker/features/Alias.kt
- src/main/kotlin/com/jaoafa/vcspeaker/stores/AliasStore.kt
- src/main/kotlin/com/jaoafa/vcspeaker/stores/IgnoreStore.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tools/Emoji.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/TextProcessor.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/Token.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/replacers/AliasReplacer.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/replacers/BaseReplacer.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/replacers/ChannelMentionReplacer.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/replacers/EmojiReplacer.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/replacers/GuildEmojiReplacer.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/replacers/RegexReplacer.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/replacers/RoleMentionReplacer.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/replacers/UrlReplacer.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/replacers/UserMentionReplacer.kt
- src/test/kotlin/TextProcessorTest.kt
Replacers が再帰的に置き換えをしないようにしました。
(たぶんまだいじります)
> feat: non recursive replacers

- src/main/kotlin/com/jaoafa/vcspeaker/tts/replacers/UrlReplacer.kt
> feat: google検索URLの特殊読み上げを追加

- src/main/kotlin/com/jaoafa/vcspeaker/tools/Twitter.kt
- src/test/kotlin/TwitterTest.kt
> fix: x.comの置き換えがされない & picだけ残る問題の修正

- src/main/kotlin/com/jaoafa/vcspeaker/tts/replacers/BaseReplacer.kt
> feat: メンションの先頭にアットマークを入れるように

- src/main/kotlin/com/jaoafa/vcspeaker/tts/MessageProcessor.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/TextProcessor.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/replacers/UrlReplacer.kt
https://github.com/jaoafa/jao-Minecraft-Server/issues/212 を修正しました。
- close #150
> fix: substring by codepoints

- src/test/kotlin/SteamTest.kt
- src/test/kotlin/TwitterTest.kt
- src/test/kotlin/YouTubeTest.kt
> test: shouldBeEqualをshouldBeに変更

- src/main/kotlin/com/jaoafa/vcspeaker/tts/MessageProcessor.kt
- close #151 
以下のような場合、test2 メッセージは `ち への返信、test2` と読み上げるようになります。
> feat: メッセージ返信の場合に、その旨を本文前に読み上げるように

- .github/workflows/codeql.yml
- .github/workflows/docker.yml
- .github/workflows/test.yml
Merge Queue を有効化しました。
close #154
> ci: enable merge queue

- src/main/kotlin/com/jaoafa/vcspeaker/events/ServerMuteEvent.kt
close #190 
サーバーミュート通知機能を実装しました。
> feat: server mute notification

- .github/workflows/docker.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- .idea/compiler.xml
- .idea/kotlinc.xml
- .idea/misc.xml
- Dockerfile
- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
- gradlew
Kotlin を v2 に、JDK を 21 に上げました。
> chore: upgrade Kotlin and JDK

- Dockerfile
https://docs.docker.com/reference/build-checks/ に基づき、Dockerfileを更新しました。
> chore: Build checksに基づいてDockerfileを更新

- .github/workflows/codeql.yml
CodeQL の Workflow が失敗 (またはフリーズ) する問題を解決~~しようとしています~~ -> しました
> ci: codeql fails

- .idea/gradle.xml
- .idea/misc.xml
- src/main/kotlin/com/jaoafa/vcspeaker/tts/replacers/UrlReplacer.kt
> feat: ニコニコ動画の動画ページタイトル読み上げへの対応

- src/main/kotlin/com/jaoafa/vcspeaker/Main.kt
接続が切断されてから 10 秒待って再接続を試みるようにしました。
close #222
> feat: connection retry

- .github/workflows/release.yml
> fix: bump version type error

- .github/workflows/release.yml
- Dockerfile
- build.gradle.kts
Shadow Jar のパスが変わったので関連ファイルを修正しました。
> fix: wrong path to shadow jar

- .github/workflows/build.yml
ビルド時にアーティファクトをアップロードするようにしました。
あと docker.yml から build.yml にリネームしました。
close #233
> ci: upload artifact

- build.gradle.kts
- src/main/kotlin/com/jaoafa/vcspeaker/Main.kt
5.0.0がリリースされたことで、インポートすべきパッケージが変わりました。
ざっとリリースノートを見る限りそれ以外のインパクトはなさそうですが、一応確認ください。
- close #226 
- close #212
> fix(deps): update dep clikt:clikt v5 & change import package

- src/main/kotlin/com/jaoafa/vcspeaker/tts/narrators/Narrator.kt
BaseProcessor.cancel() が実行された場合、以降の Processor の実行と読み上げを中止するようにしました。
これにより、/ignore しても ignore されない問題が解決されます。
close https://github.com/jaoafa/jao-Minecraft-Server/issues/227
> fix: processor cancel logic

- build.gradle.kts
相変わらず fatal error が出るので、戻します。
- Reverts jaoafa/VCSpeaker.kt#260
> Revert "chore(deps): upgrade Cloud Vision to 3.53.0"

- src/main/kotlin/com/jaoafa/vcspeaker/tools/Emoji.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tools/KtorPlugin.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tools/Steam.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tools/Twitter.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tools/YouTube.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/providers/soundmoji/SoundmojiProvider.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/providers/voicetext/VoiceTextProvider.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/replacers/UrlReplacer.kt
- close #285
ユーザーエージェントにバージョン情報を入れたければ、request changes でその旨指示ください。
> feat: 各種HTTPリクエストにユーザーエージェントを付与

- src/main/kotlin/com/jaoafa/vcspeaker/tts/processors/AttachmentProcessor.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/processors/CharLimitProcessor.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/processors/IgnoreAfterReplaceProcessor.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/processors/IgnoreBeforeReplaceProcessor.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/processors/InlineVoiceProcessor.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/processors/MarkdownFormatProcessor.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/processors/MessageTransferProcessor.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/processors/PinMessageProcessor.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/processors/ReplacerProcessor.kt
- src/main/kotlin/com/jaoafa/vcspeaker/tts/processors/StickerProcessor.kt
- src/test/kotlin/processors/MessageTransferProcessorTest.kt
> feat: 転送メッセージの読み上げ機能を実装

- src/main/kotlin/com/jaoafa/vcspeaker/tts/replacers/UrlReplacer.kt
> fix: 絵文字が含まれるツイートを読み上げる際、IndexOutOfBoundsExceptionが発生する問題を修正
