jaoafa/VCSpeaker.kt

build.gradle.kts

`com.github.aikaterna:lavaplayer-natives:original-SNAPSHOT` を依存関係に追加することにより、arm64など複数アーキテクチャでlavaplayerが動作するように修正します。
- close #7 
- see https://github.com/jaoafa/JDA-VCSpeaker/pull/228

feat: arm64などの複数アーキテクチャに対応

---

src/main/kotlin/com/jaoafa/vcspeaker/events/NewMessageEvent.kt

AFK チャンネルにいる人がメッセージを送信した際、VCSpeaker が AFK チャンネルに参加してくる問題を修正しました。

fix: bot joins afk channel when NewMessageEvent fired

---

src/main/kotlin/com/jaoafa/vcspeaker/tts/replacers/SpoilerReplacer.kt

Discord のスポイラー (`||これ||`) 記法に対応しました。
スポイラー内の文章はすべて「ピー」に置き換えられます。

feat: spoiler detection

---

src/main/kotlin/com/jaoafa/vcspeaker/tts/narrators/Narrator.kt

メッセージを送信してから読み上げられるまでが遅いことがあるので調査したところ、リアクション処理に時間がかかっていたので別スレッドでやるようにしました。
大体 0.6~0.8 秒位短縮できるはずです。
(リアクション以外の遅延はほとんど API 呼び出しと Lavaplayer のロードだったので、これでまだ遅かったらうーんです)

perf: add reaction on another thread

---

.releaserc

`perf` が `pref` になっていたので修正しました。
多分だいぶ前から間違ってました。

fix: perf commit type

---

.gitignore
Dockerfile
build.gradle.kts
src/main/kotlin/com/jaoafa/vcspeaker/VCSpeaker.kt
src/main/kotlin/com/jaoafa/vcspeaker/stores/VisionApiCounterStore.kt
src/main/kotlin/com/jaoafa/vcspeaker/tools/VisionApi.kt
src/main/kotlin/com/jaoafa/vcspeaker/tts/MessageProcessor.kt

- close #23 
vcテキストチャンネルに画像を投稿した際、Google Cloud Platform の Cloud Vision API を用いて画像内のテキストを文字起こしし、読み上げます。
また、scrimage ライブラリを用いて画像のテキスト位置に短形を描画し、テキストの位置を判別しやすくした画像を合わせて投稿します。
レスポンスは google-cloud-vision ライブラリが定義するファイル形式（JSONなどではなく、バイナリ）でキャッシュし、md5ハッシュ値が同じ画像の場合は同一レスポンスを返します。
キャッシュファイルは store/vision-api/cache/ に格納するようにしました。
割とやっつけで実装しているので、不足あればご指摘ください。
現時点でわかっている問題点として、明らかに画像の読み込み処理で時間かかって読み上げがちょっと止まるので、何らかの対応が今後必要かなとは思います。

feat: vcテキストチャンネルに画像が投稿された場合に、文字起こしする

---

.gitignore
Dockerfile

Dockerでの実行時に下記エラーが発生する問題を解消します
> Caused by: java.lang.RuntimeException: Fontconfig head is null, check your fonts or fonts configuration
ref: https://stackoverflow.com/questions/74975762/docker-and-spring-boot-giving-sun-awt-fontconfiguration-head-is-null

fix: フォントエラーを解消

---

.gitignore
.idea/kotlinc.xml
build.gradle.kts
src/main/kotlin/com/jaoafa/vcspeaker/Main.kt
src/main/kotlin/com/jaoafa/vcspeaker/tools/Emoji.kt
src/main/resources/log4j2.xml

Log4J を設定してログをちゃんと制御するようにしました。
INFO 以上のログがコンソールに、DEBUG 以上のログがファイル (./logs/vcspeaker-yyyy-mm-dd.log) に出力されます。
Kord (と Extensions) のデバッグログについては、ほぼ使ってないし、本当に出したい開発ログが流れてつらいのでコンソールには出さなくていいかなと思いました。
あと、まだ ./logs ディレクトリをほかの場所に設定できるようにはしていません。
必要なら調べて実装しますが、要りますか？
close #9

feat: configure logging by slf4j + log4j 2

---

Dockerfile
compose.yaml

- タイムゾーンを Asia/Tokyo に設定しました。
(ファイルに書き込む方法はなぜか効かなかったので、ENV に設定するようにしました)
- Gradle が依存ライブラリをダウンロードするところまでを、Docker がキャッシュできるようにしました。
- あと ./logs をボリュームに設定しました。

chore: fix timezone & make gradle deps cached

---

src/main/kotlin/com/jaoafa/vcspeaker/tts/MessageProcessor.kt

VisionAPI の設定ファイルが存在しない場合は、画像処理を無効化するようにしました。

fix: disable VisionAPI if config not exists

---

src/main/kotlin/com/jaoafa/vcspeaker/models/original/twitter/Tweet.kt
src/main/kotlin/com/jaoafa/vcspeaker/tools/Twitter.kt
src/main/kotlin/com/jaoafa/vcspeaker/tts/replacers/UrlReplacer.kt

- close #84
以下のドメインURLについて、ツイート本文に含まれる場合に読み上げないようにします。
- pic.twitter.com
- t.co
- twitter.com
また、ハッシュタグの読み上げについて特殊な読み上げを行うように変更しました。

feat: ツイートに含まれるpic.twitter.comなどのURLを読み上げないように変更

---

src/main/kotlin/com/jaoafa/vcspeaker/commands/TitleCommand.kt

- close #86 
`title` コマンドによるタイトル変更時、"タイトルを「*新しいタイトル*」に変更しました。" とシステムメッセージで読み上げるようになります。

feat: タイトル変更時に変更後のタイトルを読み上げる

---

src/main/kotlin/com/jaoafa/vcspeaker/events/VoiceJoinEvent.kt
src/main/kotlin/com/jaoafa/vcspeaker/events/VoiceLeaveEvent.kt
src/main/kotlin/com/jaoafa/vcspeaker/events/VoiceMoveEvent.kt
src/main/kotlin/com/jaoafa/vcspeaker/tts/narrators/Narrator.kt

- close #87 
BotがVCに参加・移動・退出した場合に、それの読み上げ（ナレーション）はしないものの、メッセージ投稿は行うように変更します。
なお、VCSpeaker本人（Bot自身）の場合は本機能の対象外としています。

feat: botがVCに参加・移動・退出した場合に読み上げはしないがメッセージ投稿だけ行う

---

.github/workflows/release.yml

https://www.npmjs.com/package/conventional-changelog-conventionalcommits?activeTab=versions
タイミング的に、CI が落ちるのは conventional-changelog-conventionalcommits の v8 がリリースされたことが原因だと思われるので、一時的に v7 に固定します。

fix: use conventional-changelog-conventionalcommits v7

---

Dockerfile
src/main/kotlin/com/jaoafa/vcspeaker/tts/MessageProcessor.kt

スポイラーされた画像ファイルが投稿されたとき、以下のように処理します。
- 文字起こしのメッセージでは、descriptionをスポイラーします。
- 読み上げでは、「スポイラー画像ファイル」として読み上げます。
あわせて、文字起こしメッセージ投稿とあわせてサムネイル投稿される文字箇所画像の日本語が豆腐になる問題を改善しました。

feat: スポイラーファイル投稿時、文字起こしもスポイラーする。日本語フォント対応

---

.github/workflows/release.yml

Semantic Release でのバージョン決定とリリースの間のタイミングで次のコミットがされると、それにタグがついて次のリリースが失敗する問題を修正しました。
(ブランチ名を修正)

fix: specify tag sha of release

---

renovate.json

renovateの設定について、以下の変更を加えます。
- extends -> `:disableRateLimiting` の追加
- アクティブなプルリクエスト3つという制限を外します
- timezone
- Asia/Tokyoにタイムゾーンを設定します
- automerge & platformAutomerge
- オートマージを有効にします
- ただし、`kentaro-m/auto-assign-action` によって強制的にレビュアー追加がなされるため、そのレビュアーがレビューをしない限りマージされることはありません
- platformAutomergeを有効にすることで、GitHubのAutomerge機能が動作し、レビュー完了 & CIエラーなしだったら即マージされるようになります（レビューApprove後にマージボタンを押下する必要がなくなる）
- platformCommit
- GitHubプラットフォームのコミットAPIに即するため、署名がされるようになります（たぶん）

chore: renovate設定内容の変更

---

.github/workflows/release.yml

リリース時のコミット指定がrefなことにより、"refs/heads/main" に対してタグ付けがなされている
これにより、リリース処理中に新しくコミットがマージされると、本来と異なるコミットに紐づいてしまうため、github.refではなくgithub.shaでなければだめそう。

ci: リリース時のコミット指定をハッシュに変更

---

renovate.json

mkdocs 関連の renovate updates をひとつの PR にグルーピングします。
これにより、mkdocs 本体の更新に依存するアップデート時にエラーにならなくなります。

chore(renovate): mkdocs関連をグループ化

---

src/main/kotlin/com/jaoafa/vcspeaker/tts/replacers/EmojiReplacer.kt

- close #160 
PriorityがGuildEmojiReplacerと同じになっていた影響で、サーバ絵文字のエイリアスが機能しない問題を改善します。
※このあたりの複合テスト、不足しているので別のPRで追加したいですね

fix: サーバ絵文字のエイリアスが機能しない問題の修正

---

src/main/kotlin/com/jaoafa/vcspeaker/tts/markdown/Line.kt
src/test/kotlin/processors/MarkdownFormatProcessorTest.kt

feat: `-#` のヘッダーに対応

---

src/test/kotlin/processors/ReplacerProcessorTest.kt
src/test/kotlin/replacers/AliasReplacerTest.kt
src/test/kotlin/replacers/ChannelMentionReplacerTest.kt
src/test/kotlin/replacers/EmojiReplacerTest.kt
src/test/kotlin/replacers/GuildEmojiReplacerTest.kt
src/test/kotlin/replacers/RegexReplacerTest.kt
src/test/kotlin/replacers/RoleMentionReplacerTest.kt
src/test/kotlin/replacers/UrlReplacerTest.kt
src/test/kotlin/replacers/UserMentionReplacerTest.kt

- close #177 
---
分割にあわせ、以下の複合テストを追加。
- If there is an alias for a server emoji, the EmojiReplacer should be applied.
- If there is no alias for a server emoji, the GuildEmojiReplacer should be applied.
- User mentions cannot be replaced by aliases.
- After the URL is replaced, the alias should be applied.

test: ReplacerProcessorTestの分割、Replacer複合テストの追加

---

build.gradle.kts

lavaplayer に natives が統合されたので、別で入れていた natives の依存を消去しました。(lavalink-devs/lavaplayer の # 2)

chore(deps): remove lavaplayer native

---

.github/workflows/codeql.yml
src/main/kotlin/com/jaoafa/vcspeaker/tts/markdown/Inline.kt
src/main/kotlin/com/jaoafa/vcspeaker/tts/markdown/Line.kt
src/main/kotlin/com/jaoafa/vcspeaker/tts/processors/MarkdownFormatProcessor.kt
src/test/kotlin/processors/markdown/InlineTest.kt
src/test/kotlin/processors/markdown/LineTest.kt

close https://github.com/jaoafa/jao-Minecraft-Server/issues/219
メッセージ内に `***text***` `___text___` が含まれている時に読み上げが失敗する問題を修正しました。
あとついでですが、スポイラーと取り消し線を「ピー」と「パー」に置き換える処理を Processor に移動しました。

fix: italic bold fails

---

.idea/gradle.xml
.idea/kotlinc.xml
build.gradle.kts
src/main/kotlin/com/jaoafa/vcspeaker/tools/Twitter.kt

close #218 
Ktor を v3 に上げました。
NoSuchMethodError は response.body() 内部の readRemaining() で出てそうなので、bodyAsText() からもらって手動で serialize するようにしました。
(もしかしたら kord-core が持ってる ktor v2 とのコンフリクトかもしれないけど、kord-extensions のセットアップ方法がだいぶ変わってていろいろ書き換えないといけないのでこの PR には含めてません)
あと Jericho HTML Parser がメンテナンスされてなさそうなので Jsoup に置き換えました。

fix: response.body() fails

---

build.gradle.kts

Fatal Error が発生するので、最後に正常に機能していたであろう 3.47.0 までロールバックします。
3.47.0 -> 3.50.0 に上げてたので 3.48.0 か 3.49.0 でも良いかもしれませんが... (https://github.com/jaoafa/VCSpeaker.kt/commit/c56101075e10c3ecdf0b4dda7038017ad8172047)

fix(deps): rollback cloud vision to 3.47.0

---

.idea/gradle.xml
.idea/kotlinc.xml
src/main/kotlin/com/jaoafa/vcspeaker/events/NewMessageEvent.kt
src/main/kotlin/com/jaoafa/vcspeaker/tts/narrators/Narrator.kt
src/main/kotlin/com/jaoafa/vcspeaker/tts/processors/AttachmentProcessor.kt
src/main/kotlin/com/jaoafa/vcspeaker/tts/processors/CharLimitProcessor.kt
src/main/kotlin/com/jaoafa/vcspeaker/tts/processors/IgnoreAfterReplaceProcessor.kt
src/main/kotlin/com/jaoafa/vcspeaker/tts/processors/IgnoreBeforeReplaceProcessor.kt
src/main/kotlin/com/jaoafa/vcspeaker/tts/processors/InlineVoiceProcessor.kt
src/main/kotlin/com/jaoafa/vcspeaker/tts/processors/MarkdownFormatProcessor.kt
src/main/kotlin/com/jaoafa/vcspeaker/tts/processors/PinMessageProcessor.kt
src/main/kotlin/com/jaoafa/vcspeaker/tts/processors/ReplacerProcessor.kt
src/main/kotlin/com/jaoafa/vcspeaker/tts/processors/ReplyProcessor.kt
src/main/kotlin/com/jaoafa/vcspeaker/tts/processors/StickerProcessor.kt
src/test/kotlin/processors/PinMessageProcessorTest.kt
src/test/kotlin/processors/ReplyProcessorTest.kt

feat: ピン止めメッセージの読み上げ

---

src/main/kotlin/com/jaoafa/vcspeaker/tools/discord/DiscordExtensions.kt
src/main/kotlin/com/jaoafa/vcspeaker/tts/Scheduler.kt
src/main/kotlin/com/jaoafa/vcspeaker/tts/narrators/Narrator.kt

close #298 
Bot がブロックされている時、リアクションを付けようとする際に例外が発生する問題を修正しました。

fix: ignore exceptions of blocked reactions

---

src/main/kotlin/com/jaoafa/vcspeaker/tts/replacers/UrlReplacer.kt
src/test/kotlin/replacers/UrlReplacerTest.kt

タイトルを取得しようとするドメインが存在しない場合と、タイムアウトする場合の例外をキャッチするようにしました。
「存在しないWebページへのリンク」と読み上げます。

fix: connect timeout, non-existent domains

---

src/main/kotlin/com/jaoafa/vcspeaker/stores/CacheStore.kt

存在しないレコードを参照することによる Null Pointer Exception を修正しました。
close https://github.com/jaoafa/jao-Minecraft-Server/issues/236

fix: null pointer when non-existent record check

---

src/main/kotlin/com/jaoafa/vcspeaker/stores/AliasStore.kt
src/main/kotlin/com/jaoafa/vcspeaker/stores/CacheStore.kt
src/main/kotlin/com/jaoafa/vcspeaker/stores/StoreStruct.kt

エイリアスを長い順にソートしてから適用することにより、例えば "VR", "VRAM" が存在する場合に "VR" が先に適用される問題を修正しました。
また、Store の Audit 機能を実装し、auditor を書けば、初期化時と書き込み時 (`write()`) に data を変更できるようにしました。
エイリアスのソートはこれで実装しています。
ついでに、CacheStore にも、音声ファイルが存在しないデータを削除する処理を実装しました。
close https://github.com/jaoafa/jao-Minecraft-Server/issues/237

chore: order aliases by its length, store auditor

---

build.gradle.kts
src/test/kotlin/providers/BatchProviderTest.kt
src/test/kotlin/providers/SpeechProviderTest.kt
src/test/kotlin/tools/ReflectionTest.kt
src/test/kotlin/tools/SerializationTest.kt
src/test/kotlin/tools/VisionApiTest.kt

テスト項目を GitHub Copilot に書かせました。
- 太字・斜体・打消し・下線・インラインコード・リンク・引用・spoiler・コードブロック・リスト・ヘッダー・複数行・空文字・通常文
- `MarkdownFormatProcessorTest` の各 test で網羅（例: "If the markdown message contains bold phrases..." など）
- 速度変化（ヘッダーごと）
- `MarkdownFormatProcessorTest` の "Change reading speed by header level." context
- 複数ヘッダー・境界値
- `MarkdownFormatProcessorTest` の "If there are multiple header lines..." など
- 異常系（不正なマークダウン、空文字）
- `MarkdownFormatProcessorTest` の "If the message is empty..." など
- 返信時のユーザー名取得
- `ReplyProcessorTest` の "If the message is a reply, read the author name..."
- 作者不明
- `ReplyProcessorTest` の "If the message is a reply but the author of the replied message is unknown..."
- 非返信
- `ReplyProcessorTest` の "If the message is not a reply, read it as is."
- 境界値
- 上記テストでカバー
- ピン止め通知
- …

test: テスト項目の追加

---

.github/workflows/release.yml

1.0.0がリリースされたので適用したのですが、うまく動いてませんでした。
1.0.0に対応させるためにパラメータいじってみましたが、v1で使われるようになったコマンドでは新規イメージが作られないらしく（？）、うまく動きませんでした。ので、戻します。
> ソース・マニフェストは、マニフェストリストや特定プラットフォーム用のディストリビューション・マニフェストとすることができ、**新しいマニフェストリストの作成時には、レジストリに存在していなくてはいけません。**
https://docs.docker.jp/engine/reference/commandline/buildx_imagetools_create.html
なんかわかったら教えてください。

revert: Noelware/docker-manifest-action 0.4.3に戻す

---

build.gradle.kts

特定の Bot アカウントで VC に接続する際、`4016 Unknown encryption mode` エラーが発生する問題に対応しました。
現在 Kord Voice モジュールで実装されている暗号化モードが `XSalsa20Poly1305` のみで、それが去年の終わり頃に非推奨化されたことが原因だと思われます。 [Discord Developer Portal - Transport Encryption Modes](https://discord.com/developers/docs/topics/voice-connections#transport-encryption-modes)
幸運なことにそれに対応するスナップショットが公開されていたので、それを使うようにしました。
Kord リポジトリの PR #990 で対応されているようです。

fix: use kord-voice snapshot for new encryption mode
